/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpcfs.h"
#include <sys/types.h>

bool_t
xdr_read_data (XDR *xdrs, read_data *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->n_byte))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->offset))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->file_name, 128,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_read_result (XDR *xdrs, read_result *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->bytes_read))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->buf, 1024,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_write_data (XDR *xdrs, write_data *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->file_name, 128,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->n_byte))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->buf, 1024,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
