/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TIMEBREAK_H_RPCGEN
#define _TIMEBREAK_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define TIMEBREAK_PROG 555553555
#define TIMEBREAK_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define TIMEBREAK 1
extern  int * timebreak_1(long *, CLIENT *);
extern  int * timebreak_1_svc(long *, struct svc_req *);
#define CONNECT 2
extern  int * connect_1(void *, CLIENT *);
extern  int * connect_1_svc(void *, struct svc_req *);
extern int timebreak_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define TIMEBREAK 1
extern  int * timebreak_1();
extern  int * timebreak_1_svc();
#define CONNECT 2
extern  int * connect_1();
extern  int * connect_1_svc();
extern int timebreak_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TIMEBREAK_H_RPCGEN */
