/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPCFS_H_RPCGEN
#define _RPCFS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#include <sys/types.h>

struct read_data {
	int n_byte;
	int offset;
	char file_name[128];
};
typedef struct read_data read_data;

struct read_result {
	int bytes_read;
	char buf[256];
};
typedef struct read_result read_result;

struct write_data {
	char file_name[128];
	int n_byte;
	char buf[256];
};
typedef struct write_data write_data;

#define RPCFS_PROG 555555555
#define RPCFS_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define READ 1
extern  read_result * read_1(read_data *, CLIENT *);
extern  read_result * read_1_svc(read_data *, struct svc_req *);
#define WRITE 2
extern  int * write_1(write_data *, CLIENT *);
extern  int * write_1_svc(write_data *, struct svc_req *);
extern int rpcfs_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define READ 1
extern  read_result * read_1();
extern  read_result * read_1_svc();
#define WRITE 2
extern  int * write_1();
extern  int * write_1_svc();
extern int rpcfs_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_read_data (XDR *, read_data*);
extern  bool_t xdr_read_result (XDR *, read_result*);
extern  bool_t xdr_write_data (XDR *, write_data*);

#else /* K&R C */
extern bool_t xdr_read_data ();
extern bool_t xdr_read_result ();
extern bool_t xdr_write_data ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPCFS_H_RPCGEN */
