/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _VADD_H_RPCGEN
#define _VADD_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef struct {
	u_int iarray_len;
	int *iarray_val;
} iarray;

#define VADD_PROG 555575555
#define VADD_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define VADD 1
extern  int * vadd_1(iarray *, CLIENT *);
extern  int * vadd_1_svc(iarray *, struct svc_req *);
extern int vadd_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define VADD 1
extern  int * vadd_1();
extern  int * vadd_1_svc();
extern int vadd_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_iarray (XDR *, iarray*);

#else /* K&R C */
extern bool_t xdr_iarray ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_VADD_H_RPCGEN */
