/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */


#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

#include "ll.h"


/* remote procedure that sums the ints in the linked list */ 

int *
sum_1_svc(foo *argp, struct svc_req *rqstp)
{
	static int  result;

    // error
    // exit(1);

    // sleep for client error
    sleep(30);   

	result=0;
	while (argp) {
	  result += argp->x;
	  argp = argp->next;
	}

	return (&result);
}



