/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "userlookup.h"

bool_t
xdr_username (XDR *xdrs, username *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, 10))
		 return FALSE;
	return TRUE;
}
